using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("3.0.0.99")]
[assembly: AssemblyFileVersionAttribute("3.0.0.99")]
[assembly: AssemblyCopyrightAttribute("Copyright © MVC Contrib 2007-2011")]
[assembly: AssemblyProductAttribute("MVCContrib")]
[assembly: AssemblyCompanyAttribute("MVC Contrib")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("3.0.0.99")]

